name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.4

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./i18n/vscode-language-pack-cs
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-cs
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-de
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-de
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-es
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-es
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-fr
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-fr
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-it
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-it
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-ja
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-ja
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-ko
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-ko
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-pl
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-pl
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-pt-BR
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-pt-BR
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-qps-ploc
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-qps-ploc
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-ru
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-ru
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-tr
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-tr
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-zh-hans
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-zh-hans
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./i18n/vscode-language-pack-zh-hant
              continue-on-error: true
              working-directory: ./i18n/vscode-language-pack-zh-hant
              run: |
                  npm install --include prod dev optional peer --legacy-peer-deps
                  npm publish --legacy-peer-deps --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
